### ISSUE TITLE
Compiling with clang fails (OS X)

### ISSUE THREAD

**Issue by lloeki** [hashcat/hashcat#48]
Clang output:

```
In file included from src/engine.c:14:
src/sha1-sse2.c:41:33: error: assigning to '__m128i' (vector of 2 'long long' values) from incompatible type 'int'
  for (i = 0; i < 16; i++) W[i] = SWAP32_SSE (W[i]);
                                ^ ~~~~~~~~~~~~~~~~~
In file included from src/engine.c:15:
src/sha256-sse2.c:59:33: error: assigning to '__m128i' (vector of 2 'long long' values) from incompatible type 'int'
  for (i = 0; i < 16; i++) W[i] = SWAP32_SSE (W[i]);
                                ^ ~~~~~~~~~~~~~~~~~
In file included from src/engine.c:17:
src/sha512-sse2.c:166:33: error: assigning to '__m128i' (vector of 2 'long long' values) from incompatible type 'int'
  for (i = 0; i < 16; i++) W[i] = SWAP64_SSE (W[i]);
                                ^ ~~~~~~~~~~~~~~~~~
3 errors generated.
make: *** [obj/engine.OSX.64.o] Error 1
```

Yet it works with Apple's LLVM-gcc, and also works with Homebrew's latest gcc (5.3 with multilib as of today). I don't know what this entails for the multilib requirement though.

See also: https://github.com/Homebrew/homebrew/pull/47815
